pipeline_template: rpm/Jenkinsfile
email_reply_to: platform-integrity-c4ssh@salesforce.com
compliance_required: false                              # (Optional) default = true
docker_test_images:                                     # The image(s) that will be used to run your unit tests (Unit tests will be run against each image)
    - sfci/kuleana/rust-builder/kuleana-rust-builder:35
    - sfci/kuleana/rust-builder/kuleana-rhel9-rust-builder:latest
unit_tests_command: STRATA=yes ./test.sh                # The command we'll run for the unit tests stage
docker_package_images: 
    - sfci/kuleana/rust-builder/kuleana-rust-builder:35      # The image that will be used to package your RPM
    - sfci/kuleana/rust-builder/kuleana-rhel9-rust-builder:latest      # The image that will be used to package your RPM
package_generation_command: ./build.sh                  # The command we'll run to package your RPMs
package_repository: kuleana                             # Please see the list of available yum repos and create a PR if your group
promote_to_falcon: true
docker_images:                                          # Provide a map of image names to custom Dockerfile names
   kuleana-tacrust: ./Dockerfile
