listen_address = "127.0.0.1:4949"
key = "tackey"

[[user]]
name = "krkhan"
credentials.type = "Ascii"
credentials.value = "helloworld"

[[user]]
name = "rahulyadav"
credentials.type = "Ascii"
credentials.value = "hellouniverse"

