listen_address = "127.0.0.1:4949"
key = "tackey"

[[acl]]
permit = [
    '^127\.0\.0\.\d{1,3}$',
    '^10\.\d{1,3}.\d{1,3}.\d{1,3}',
]

[[acl]]
permit = [
    '^172\.0\.0\.\d{1,3}$',
    '^20\.\d{1,3}.\d{1,3}.\d{1,3}',
]

[[user]]
name = "krkhan"
credentials.type = "Ascii"
# plaintext: "helloworld"
credentials.value = "$6$4Q1OSpnJ.0z1p$zA3G.m2817WlmyTOQSn/mjq.j3AH6AorPXuztfKy1FK2XJUonk/oXimh/fJq0/2ktuYUGf83LPb5sGUv9RBxp/"

[[user]]
name = "rahulyadav"
credentials.type = "Ascii"
# plaintext: "hellouniverse"
credentials.value = "$6$nEANqKsnkVf$LZWrgMg3LiZpfv4k0igYKjYAwvBYb9b/7OGh6o40uNTNNkaQcxHIYzC5UpS0.K/9OX5vbNOrLWhQ8iwwgdNNd0"

[[user]]
name = "k.khan"
credentials.type = "Pam"

